### ISSUE TITLE
Bug: can't load unum-cloud/uform-vl-english

### ISSUE THREAD

**Issue by beaugunderson** [unum-cloud/uform#28]
uform==0.2.1

```python
import uform

model = uform.get_model('unum-cloud/uform-vl-english')
```

result:

```Fetching 4 files: 100%|████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 37035.80it/s]
lib/python3.11/site-packages/timm/models/_factory.py:114: UserWarning: Mapping deprecated model name deit3_base_patch16_224_in21ft1k to current deit3_base_patch16_224.fb_in22k_ft_in1k.
  model = create_fn(
Traceback (most recent call last):
  File "t.py", line 5, in <module>
    model = uform.get_model('unum-cloud/uform-vl-english')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "lib/python3.11/site-packages/uform.py", line 484, in get_model
    model.text_encoder.load_state_dict(state['text_encoder'])
  File "lib/python3.11/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TextEncoder:
	Unexpected key(s) in state_dict: "backbone.embeddings.position_ids".```

**Comment by ashvardanian** [comment]
@VoVoR and @kimihailv have we seen such issues before? Can this be coming from HuggingFace?

**Comment by ashvardanian** [comment]
Thank you, @beaugunderson! There was a breaking change in HuggingFace API. We have now patched it. Please upgrade UForm to `v0.3.0` 🤗
